import Head from "next/head";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import Home from "@/components/Home";
import Features from "@/components/Features";
import FAQ from "@/components/FAQ";

export default function Index() {
  return (
    <>
      <Head>
        <title>My Campus Admin - MCA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Navbar />
        <Home />
        <Features />
        <FAQ />
      </main>
    </>
  );
}
